### ISSUE TITLE
Minimum or Maximum selection

### ISSUE THREAD

**Issue by shenglim** [mateuszmarkowski/jQuery-Seat-Charts#24]
Hi, how can we set maximum and minimum selection of the seats?

**Comment by mateuszmarkowski** [comment]
Currently there's no built-in feature for that. You would have to implement your own logic for example when user submits the checkout form. The easiest way to find out how many seats have been selected will be:
`
$('#seat-map'). seatCharts().find('selected').length
`
If the length is within your required limit, user can submit the form, otherwise you will display an error message.

**Comment by shenglim** [comment]
Alright, thank you very much !
